theme: jekyll-theme-midnight
title: Customizable Gesture-Based Assistive Control System
description: >-
  2020 Fall ECE M202A/CS M213A Embedded Systems Final Project
  
  Andrew Ho, Tu Yu Hsien, Jessica Bojorquez
